In [1]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler

In [2]:
boston=load_boston()

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [3]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename', 'data_module'])

In [4]:
print(boston['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [5]:
df=pd.DataFrame(boston['data'],columns=boston['feature_names'])
print(df)
df['Price']=boston['target']

        CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       1

In [6]:
df.corr()['Price']

CRIM      -0.388305
ZN         0.360445
INDUS     -0.483725
CHAS       0.175260
NOX       -0.427321
RM         0.695360
AGE       -0.376955
DIS        0.249929
RAD       -0.381626
TAX       -0.468536
PTRATIO   -0.507787
B          0.333461
LSTAT     -0.737663
Price      1.000000
Name: Price, dtype: float64

In [7]:
scaler=StandardScaler()
X=scaler.fit_transform(df.drop('Price',axis=1))
y=df['Price']

In [8]:
X

array([[-0.41978194,  0.28482986, -1.2879095 , ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, ..., -0.30309415,
         0.44105193, -0.49243937],
       [-0.41734159, -0.48772236, -0.59338101, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.98304761],
       [-0.40776407, -0.48772236,  0.11573841, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [-0.41500016, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.66905833]])

In [9]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: Price, Length: 506, dtype: float64

In [10]:
#regressión lineal tipo Ridge
ridge=Ridge()
ridge_20=Ridge(alpha=20)

ridge_9_99=Ridge(alpha=9.99)

In [49]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=98)
y_test

286    20.1
352    18.6
468    19.1
225    50.0
452    16.1
       ... 
378    13.1
408    17.2
219    23.0
224    44.8
78     21.2
Name: Price, Length: 102, dtype: float64

In [28]:
ridge.fit(X_train,y_train)
ridge_9_99.fit(X_train,y_train)

Ridge(alpha=9.99)

In [29]:
ridge_20.fit(X_train,y_train)

Ridge(alpha=20)

In [34]:
r_train_score=ridge.score(X_train,y_train)
r_test_score=ridge.score(X_test,y_test)

r_9_train_score=ridge_9_99.score(X_train,y_train)
r_9_test_score=ridge_9_99.score(X_test,y_test)

r20_train_score=ridge_20.score(X_train,y_train)
r20_test_score=ridge_20.score(X_test,y_test)

In [36]:
r_train_score,r_9_train_score,r20_train_score

(0.7293364014235403, 0.7279445275454266, 0.7253683296699814)

In [37]:
r_test_score,r_9_test_score,r20_test_score

(0.763389008406695, 0.7615399531864019, 0.7579760693190633)

In [ ]:
grid

In [ ]:
y_test

173    23.6
274    32.4
491    13.6
72     22.8
452    16.1
       ... 
412    17.9
436     9.6
411    17.2
86     22.5
75     21.4
Name: Price, Length: 102, dtype: float64

In [ ]:
ridge_20.predict(X_test)

array([28.59168884, 35.26039435, 16.12148628, 24.8659174 , 18.7041308 ,
       23.27118134, 18.01323668, 14.85364532, 22.26927897, 20.88540237,
       24.58162138, 19.25095337, -5.20390864, 22.04212279, 19.36176275,
       25.6706509 , 19.568965  ,  5.91274737, 39.61102215, 17.59075106,
       26.73733633, 29.23526647, 12.13741791, 24.26207224, 17.66805321,
       15.29538194, 22.79921325, 14.87637149, 22.52844746, 19.53299195,
       22.1222618 , 25.21387798, 25.5960488 , 17.46881055, 16.3621481 ,
       17.62419194, 31.21633938, 20.26698867, 23.89971219, 24.55339497,
       14.44125654, 31.11949029, 41.24383393, 17.91775501, 27.22309669,
       16.72617652, 14.61213036, 25.80784569, 19.83052506, 30.18822462,
       21.67805294, 33.62392214, 16.67183035, 26.41367159, 38.77894938,
       22.22287841, 18.76038562, 31.64169708, 25.11200714, 13.63450478,
       23.04999361, 30.18676448, 30.85126315, 16.26839141, 21.79483952,
       16.93415144, 20.26443272, 25.80579184, 29.91572783, 11.79

In [ ]:
print(ridge.coef_) #aquí sacas los coefs de las pendientes 
print(ridge_20.coef_)

[-0.96203397  0.68255872  0.25071604  0.71033762 -1.96157279  3.12232106
 -0.17845861 -3.0100255   2.20195592 -1.71784558 -1.97082455  1.12414013
 -3.61478723]
[-0.84416652  0.46198062 -0.03418626  0.75114482 -1.53723325  3.17316115
 -0.1880602  -2.48151078  1.31849282 -0.97365431 -1.83807721  1.08177436
 -3.40377171]


In [ ]:
Precio=-0.96*CRIM  +0.68*INDUS +0.25*CHAS +....... 1.12*LSTAT -3.16*MEDV +22.48

y=mx

In [ ]:
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
        - B        1000(Bk - 0.63)^2 where Bk is the proportion of black people by town
        - LSTAT    % lower status of the population
        - MEDV    

In [ ]:
ridge.intercept_ #sacas la "b" de la eq. de la recta, la ordenada al origen

22.484854796146763

In [38]:
linreg=LinearRegression()
linreg.fit(X_train,y_train)

l_test_score=linreg.score(X_test,y_test)
r_test_score=ridge.score(X_test,y_test)
r20_test_score=ridge_20.score(X_test,y_test)
r9_99_test_score=ridge_9_99.score(X_test,y_test)

In [39]:
l_test_score,r_test_score,r20_test_score

(0.7634174432138471, 0.763389008406695, 0.7579760693190633)

In [40]:
(y_test-linreg.predict(X_test)).sum()

-26.210861929712564

In [41]:
(y_test-ridge.predict(X_test)).sum()

-26.81863446682887

In [42]:
(y_test-ridge_20.predict(X_test)).sum()

-31.060118085552794

In [43]:
(y_test-ridge_9_99.predict(X_test)).sum()

-30.011537915853353

In [46]:
(y_train-linreg.predict(X_train)).sum()

1.0089706847793423e-12

In [45]:
(y_train-ridge_9_99.predict(X_train)).sum()

3.623767952376511e-13

In [79]:
from sklearn.model_selection import GridSearchCV, RepeatedKFold
cv=RepeatedKFold(n_splits=3,n_repeats=10,random_state=425) #Cross-validation

grid=dict()
grid['alpha']=np.arange(0,10,0.01)



In [89]:
ridge_best=Ridge()

best_param=GridSearchCV(ridge_best,grid,cv=cv,n_jobs=-1,scoring='r2')

In [90]:
import time
start=time.time()
results=best_param.fit(X_train,y_train)
print(time.time()-start)

42.04174304008484


In [91]:
results.best_params_ 

{'alpha': 8.85}

In [62]:
el_mejor=Ridge()
el_mejor=Ridge(alpha=5.86)

In [63]:
el_mejor.fit(X_train,y_train)

Ridge(alpha=5.86)

In [64]:
el_mejor.predict(X_train)

array([31.21122923, 24.46689538, 17.10614184, 27.08242121, 19.22836531,
       12.67258735, 34.8138494 , 23.27270367, 20.61264017, 15.80924749,
       23.75099539, 27.52954508, 38.72946381,  9.96840411, 33.81924299,
       24.35685721, 18.31869995, 17.30230562, 21.52027917, 11.38957497,
       18.67002195, 24.38700887, 14.05571335, 19.12376095, 14.88478025,
       20.02964611, 33.08629032, 14.05645815, -3.59750047, 16.29550684,
       12.99928011, 20.4380082 , 14.94032284, 13.55709886, 31.06630772,
        4.79182536, 28.32795843, 32.83474755, 27.34728493, 18.44757067,
       17.71090397, 32.66585076, 36.03036016,  8.55295743, 28.44282848,
       20.20566277, 21.00169857, 23.10027713, 33.17801798, 13.86617082,
       25.32900039, 24.86032837, 20.85586406, 20.40093503, 13.11059203,
       24.29975192, 18.46129725, 21.33910694, 28.38996814, 32.43521946,
       21.77732065, 19.572789  , 20.20683224, 26.47354821, 26.95456759,
       16.48019807,  8.13569383, 22.22469883, 19.41390525, 17.36

In [65]:
(y_test-el_mejor.predict(X_test)).sum()

-62.80100197459324

286    20.1
352    18.6
468    19.1
225    50.0
452    16.1
       ... 
378    13.1
408    17.2
219    23.0
224    44.8
78     21.2
Name: Price, Length: 102, dtype: float64

In [92]:
#####
#Regresión LASSO

import pandas as pd
import numpy as np 

from sklearn.linear_model import Lasso, ElasticNet
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

In [93]:
data=pd.read_csv('https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/insurance.csv')

In [94]:
data.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [95]:
data.keys()

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [96]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [98]:
for col in data.columns:
  if data[col].dtype =='object':
    print(col,data[col].unique())

sex ['female' 'male']
smoker ['yes' 'no']
region ['southwest' 'southeast' 'northwest' 'northeast']


In [99]:
one_hot=OneHotEncoder()

one_hot.fit(data[['sex']]).categories_

[array(['female', 'male'], dtype=object)]

In [101]:
data[['female','male']]=one_hot.fit_transform(data[['sex']]).toarray()

data

age     sex     bmi  children smoker     region      charges  female  \
0      19  female  27.900         0    yes  southwest  16884.92400     1.0   
1      18    male  33.770         1     no  southeast   1725.55230     0.0   
2      28    male  33.000         3     no  southeast   4449.46200     0.0   
3      33    male  22.705         0     no  northwest  21984.47061     0.0   
4      32    male  28.880         0     no  northwest   3866.85520     0.0   
...   ...     ...     ...       ...    ...        ...          ...     ...   
1333   50    male  30.970         3     no  northwest  10600.54830     0.0   
1334   18  female  31.920         0     no  northeast   2205.98080     1.0   
1335   18  female  36.850         0     no  southeast   1629.83350     1.0   
1336   21  female  25.800         0     no  southwest   2007.94500     1.0   
1337   61  female  29.070         0    yes  northwest  29141.36030     1.0   

      male  
0      0.0  
1      1.0  
2      1.0  
3      1.0  
4      1.0  
...    ...  
1333   1.0  
1334   0.0  
1335   0.0  
1336   0.0  
1337   0.0  

[1338 rows x 9 columns]

In [102]:
data['smoker']=data['smoker'].apply(lambda x:1 if x=='yes' else 0 )
data.head()

age     sex     bmi  children  smoker     region      charges  female  male
0   19  female  27.900         0       1  southwest  16884.92400     1.0   0.0
1   18    male  33.770         1       0  southeast   1725.55230     0.0   1.0
2   28    male  33.000         3       0  southeast   4449.46200     0.0   1.0
3   33    male  22.705         0       0  northwest  21984.47061     0.0   1.0
4   32    male  28.880         0       0  northwest   3866.85520     0.0   1.0

In [117]:
one_hot=OneHotEncoder()
regions=data['region'].unique()
regions.sort()
regions

array(['northeast', 'northwest', 'southeast', 'southwest'], dtype=object)

In [118]:
data[regions]=one_hot.fit_transform(data[['region']]).toarray()

In [119]:
data[regions]

northeast  northwest  southeast  southwest
0           0.0        0.0        0.0        1.0
1           0.0        0.0        1.0        0.0
2           0.0        0.0        1.0        0.0
3           0.0        1.0        0.0        0.0
4           0.0        1.0        0.0        0.0
...         ...        ...        ...        ...
1333        0.0        1.0        0.0        0.0
1334        1.0        0.0        0.0        0.0
1335        0.0        0.0        1.0        0.0
1336        0.0        0.0        0.0        1.0
1337        0.0        1.0        0.0        0.0

[1338 rows x 4 columns]

In [120]:
data

age     sex     bmi  children  smoker     region      charges  female  \
0      19  female  27.900         0       1  southwest  16884.92400     1.0   
1      18    male  33.770         1       0  southeast   1725.55230     0.0   
2      28    male  33.000         3       0  southeast   4449.46200     0.0   
3      33    male  22.705         0       0  northwest  21984.47061     0.0   
4      32    male  28.880         0       0  northwest   3866.85520     0.0   
...   ...     ...     ...       ...     ...        ...          ...     ...   
1333   50    male  30.970         3       0  northwest  10600.54830     0.0   
1334   18  female  31.920         0       0  northeast   2205.98080     1.0   
1335   18  female  36.850         0       0  southeast   1629.83350     1.0   
1336   21  female  25.800         0       0  southwest   2007.94500     1.0   
1337   61  female  29.070         0       1  northwest  29141.36030     1.0   

      male  southwest  southeast  northwest  northeast  
0      0.0        1.0        0.0        0.0        0.0  
1      1.0        0.0        1.0        0.0        0.0  
2      1.0        0.0        1.0        0.0        0.0  
3      1.0        0.0        0.0        1.0        0.0  
4      1.0        0.0        0.0        1.0        0.0  
...    ...        ...        ...        ...        ...  
1333   1.0        0.0        0.0        1.0        0.0  
1334   0.0        0.0        0.0        0.0        1.0  
1335   0.0        0.0        1.0        0.0        0.0  
1336   0.0        1.0        0.0        0.0        0.0  
1337   0.0        0.0        0.0        1.0        0.0  

[1338 rows x 13 columns]

In [121]:
df_clean=data.drop(columns=['sex','region'])
df_clean

age     bmi  children  smoker      charges  female  male  southwest  \
0      19  27.900         0       1  16884.92400     1.0   0.0        1.0   
1      18  33.770         1       0   1725.55230     0.0   1.0        0.0   
2      28  33.000         3       0   4449.46200     0.0   1.0        0.0   
3      33  22.705         0       0  21984.47061     0.0   1.0        0.0   
4      32  28.880         0       0   3866.85520     0.0   1.0        0.0   
...   ...     ...       ...     ...          ...     ...   ...        ...   
1333   50  30.970         3       0  10600.54830     0.0   1.0        0.0   
1334   18  31.920         0       0   2205.98080     1.0   0.0        0.0   
1335   18  36.850         0       0   1629.83350     1.0   0.0        0.0   
1336   21  25.800         0       0   2007.94500     1.0   0.0        1.0   
1337   61  29.070         0       1  29141.36030     1.0   0.0        0.0   

      southeast  northwest  northeast  
0           0.0        0.0        0.0  
1           1.0        0.0        0.0  
2           1.0        0.0        0.0  
3           0.0        1.0        0.0  
4           0.0        1.0        0.0  
...         ...        ...        ...  
1333        0.0        1.0        0.0  
1334        0.0        0.0        1.0  
1335        1.0        0.0        0.0  
1336        0.0        0.0        0.0  
1337        0.0        1.0        0.0  

[1338 rows x 11 columns]

In [123]:
X_train,X_test,y_train,y_test=train_test_split(df_clean.drop('charges',axis=1),
                                               df_clean['charges'],
                                               test_size=0.2,random_state=798)

In [124]:
#Lasso: Least Absolute shrinkage and selection operator
lasso=Lasso() #Lasso(alpha=10)
lasso.fit(X_train,y_train)

Lasso()

In [125]:
lasso.coef_

array([  254.68768561,   363.54905409,   492.3492689 , 23465.41023547,
         193.97066591,    -0.        ,  -732.04531807,  -707.20728694,
           0.        ,   555.59962592])

In [134]:
ridge=Ridge()
ridge.fit(X_train,y_train)

ridge20=Ridge(alpha=20)
ridge20.fit(X_train,y_train)

Ridge(alpha=20)

In [129]:
ridge.coef_

array([  254.44295099,   363.49146393,   492.45235674, 23339.23166925,
          95.31363444,   -95.31363444,  -515.71837007,  -480.71891986,
         219.19289723,   777.24439269])

In [132]:
lasso.predict(X_test[:10])

array([ 9318.92774733, 37750.98987082, 10634.0782061 ,  7854.12325992,
        4215.83849703, 10283.22060087,  8738.33473561, 31526.14793776,
       13166.72494269,  4899.07173032])

In [133]:
ridge.predict(X_test[:10])

array([ 9351.66564362, 37647.44122505, 10653.36257263,  7876.30067334,
        4246.99134904, 10306.32676547,  8768.32646202, 31426.21912816,
       13193.74357335,  4935.68798472])

In [135]:
ridge20.predict(X_test[:10])

array([ 9911.48482322, 35638.70931863, 10926.88205582,  8197.51362899,
        4764.18965868, 10629.05872167,  9326.16649571, 29501.46825921,
       13677.94959747,  5699.07390385])

In [136]:
y_test[:10]

145      5138.25670
1096    44641.19740
447     11454.02150
183      7419.47790
692      2362.22905
520     25656.57526
596      7640.30920
376     21659.93010
138     27322.73386
470      2497.03830
Name: charges, dtype: float64

In [137]:
forest=RandomForestRegressor(n_estimators=100,max_depth=4,random_state=12)
forest.fit(X_train,y_train)

RandomForestRegressor(max_depth=4, random_state=12)

In [139]:
lasso.predict(X_test[:10])

array([ 9318.92774733, 37750.98987082, 10634.0782061 ,  7854.12325992,
        4215.83849703, 10283.22060087,  8738.33473561, 31526.14793776,
       13166.72494269,  4899.07173032])

In [140]:
forest.predict(X_test[:10])

array([ 6539.28954531, 44590.07400772, 12906.62008644,  8863.3057448 ,
        3530.48763592, 10906.11565509,  6998.94765703, 19983.15420287,
       13745.59923983,  5032.64651309])

In [142]:
y_test[:10]

145      5138.25670
1096    44641.19740
447     11454.02150
183      7419.47790
692      2362.22905
520     25656.57526
596      7640.30920
376     21659.93010
138     27322.73386
470      2497.03830
Name: charges, dtype: float64

In [145]:
from sklearn.tree import export_graphviz
import pydot

In [150]:
rf_small=RandomForestRegressor(n_estimators=10,max_depth=7)
rf_small.fit(X_train,y_train)

tree_small= rf_small.estimators_[9]

export_graphviz(tree_small,out_file='small_tree.dot')
(graph, )=pydot.graph_from_dot_file('small_tree.dot')
graph.write_png('small_tree.png')